### ISSUE TITLE
Possibility to import font from URL or from file

### ISSUE THREAD

**Issue by GreepTheSheep** [codecat/tm-better-chat#17]
Would be nice to import more fonts from an URL.

For from file, it would be cool to create a folder in our Openplanet User folder that contains fonts.
Another thing is, if it's possible, to load Windows fonts from C:\Windows\Fonts. Up to you

**Comment by codecat** [comment]
This is already possible! As described in the settings dialog:

![image](https://user-images.githubusercontent.com/136534/146834133-901e2b1c-e807-4e30-a022-a2e520b655bc.png)

**Comment by GreepTheSheep** [comment]
ok i'm stupid LUL
