### ISSUE TITLE
Possibility to hide BetterChat on hide game interface

### ISSUE THREAD

**Issue by GreepTheSheep** [codecat/tm-better-chat#22]
Adding an option to hide on game interface

**Comment by codecat** [comment]
Starting to think whether this might be better as an Openplanet global option instead of doing this per plugin. Many plugins don't rely on this behavior now, for example Ultimate Medals doesn't do this.

Also, the weird offset trick with the Dev namespace could be avoided completely then.

**Comment by Phlarx** [comment]
( ultimate medals actually does do this, but I agree with the sentiment: https://github.com/Phlarx/tm-ultimate-medals/blob/4a07131f8e17aaf9b944b929147207f1ed12a9c3/UltimateMedals.as#L198-L203 )

**Comment by codecat** [comment]
Since Openplanet now has an option for this, I think I can close this issue.
