### ISSUE TITLE
Add support of messages with line breaks

### ISSUE THREAD

**Issue by AmazingBeu** [codecat/tm-better-chat#28]
Server controllers can send messages with line breaks, but these are displayed in a single line in better chat

**Comment by codecat** [comment]
Do you have an example of this? What are server controllers using this for?

**Comment by AmazingBeu** [comment]
> What are server controllers using this for?
Mine at least :rofl: 
![betterchat-linebreak-defaultchat](https://user-images.githubusercontent.com/26152831/147409396-8e07aa3f-5bb6-4fa9-955c-ca1cc021db31.png)
![betterchat-linebreak](https://user-images.githubusercontent.com/26152831/147409397-0df77272-6e80-44d1-8969-54ce91bcbf37.png)

**Comment by codecat** [comment]
Right, I think this was an intentional measure against people abusing newlines in chat.. perhaps we can force this in Json formatted messages.

**Comment by AmazingBeu** [comment]
Another exemple when i send in the chat a XMLRPC error as I receive it:
![betterchat-linebreak](https://user-images.githubusercontent.com/26152831/150634180-cb69affc-f085-4a0d-b1c5-0ef0fce6bb0e.png)
with the IG chat:
![regular chat](https://user-images.githubusercontent.com/26152831/150634182-fc8944e6-3d85-46b3-b0a6-30c70f2ae024.png)

**Comment by codecat** [comment]
Hmm that's a better use case.. perhaps Better Chat should just allow newlines 😅
