### ISSUE TITLE
Detect when player is typing in a manialink entry or other

### ISSUE THREAD

**Issue by AmazingBeu** [codecat/tm-better-chat#29]
when I type in the interface of my server controller, Better chat will capture my chat every time I press the T key for example, or show me the chat when I press the C key, etc....

This makes it very annoying to manage a server with better chat enabled

**Comment by codecat** [comment]
Do you have a server where I can test this?

**Comment by AmazingBeu** [comment]
You can connect on the server "Physics Controller", all the numeric values on the left panel are manialink entries

**Comment by codecat** [comment]
I've fixed this, but it will require another Openplanet update (1.21.4), which will delay the deployment of this fix a little bit.
