### ISSUE TITLE
Hide on hidden interface

### ISSUE THREAD

**Issue by Flirno** [codecat/tm-better-chat#30]
I wonder why not every plugin have that parameter by default it's a must have for me :3 
I can't use it how it is at the moment because can't focus :(

HUD ON
![Trackmania2022-1-8-23-11-51](https://user-images.githubusercontent.com/34623058/148661676-1c379b82-fb2b-44ed-a0f4-9778897fd3ad.jpg)

HUD OFF
![Trackmania2022-1-8-23-11-53](https://user-images.githubusercontent.com/34623058/148661678-7c55d9ad-4805-4442-b40a-0983bb7e1579.jpg)

**Comment by codecat** [comment]
As of recently, this is a built-in feature of Openplanet itself. Simply turn it on in the Openplanet settings.

**Comment by Flirno** [comment]
Wow epic Thanks it works perfectly!
