### ISSUE TITLE
Edit Settings or Re-Run Initial Setup?

### ISSUE THREAD

**Issue by sstream17** [codecat/tm-better-chat#31]
Is there any way to edit settings like font size etc after the initial setup has already been run?
I feel like I'm just missing a button or menu somewhere.

Thanks!

**Comment by sstream17** [comment]
Found it! It's in Openplanet > Settings.

**Comment by codecat** [comment]
Additionally you can re-run the initial setup by typing `/bc-wizard` in chat.

**Comment by sstream17** [comment]
Thanks for the reply! That is good to know too.
