### ISSUE TITLE
[Cosmetic] Duplicate https:// on link hover

### ISSUE THREAD

**Issue by DeafChips** [codecat/tm-better-chat#32]
As title suggests, extra https:// prefixed on hover:

![image](https://user-images.githubusercontent.com/90581578/148989410-2e18d8f7-7a5b-4a0e-b2b0-c41627dd672b.png)

**Comment by codecat** [comment]
What is the actual text of the message?

**Comment by DeafChips** [comment]
The first line produces the bug (space between $l and link) whereas the second line works as intended:
![image](https://user-images.githubusercontent.com/90581578/149027443-41bdf300-5383-4a2e-bead-1a1b6763a8fb.png)
