### ISSUE TITLE
[Feature] Add pad support for minimize, maximize and hide chat

### ISSUE THREAD

**Issue by xYoYoKid** [codecat/tm-better-chat#33]
Hello,
    It would be great if the better chat would have pad support as the old Nadeo chat has. For example, I was using my "c" key (keyboard) or my "down arrow" key (pad) to maximize, hide and minimize, in that order, my chat. 
    Essentially, I would like to bind one of my pad's keys ("down arrow" for me) to Openplanet -> Settings -> Better Chat -> Keys -> Toggle chat window visibility and Toggle big chat window.
Thanks!

**Comment by codecat** [comment]
I've added this under Keys as a separate option. Defaults to "None".

![image](https://user-images.githubusercontent.com/136534/153772587-b5269bf8-4966-4587-984a-5fa82359c395.png)
