### ISSUE TITLE
Team colours incorrect in royal

### ISSUE THREAD

**Issue by zai-tm** [codecat/tm-better-chat#64]
In royal, the colour that each player uses in chat is completely random and doesn't match the team.
![](https://cdn.discordapp.com/attachments/1046935339262029865/1117565580510232616/image.png)
(Better chat)
![](https://cdn.discordapp.com/attachments/1046935339262029865/1117565596746399824/image.png)
(My team)
![](https://cdn.discordapp.com/attachments/1046935339262029865/1117565680666017832/image.png)
(Ingame team chat colour)

**Comment by codecat** [comment]
Leaving this issue open for now as it seems like dedicated servers might not send the correct color.

**Comment by zai-tm** [comment]
This was fixed with the Rally update.
