### ISSUE TITLE
[Feature Request] Transparent background when OP menu is hidden

### ISSUE THREAD

**Issue by salem83** [codecat/tm-better-chat#78]
When chat is in small mode (just in the corner bottom left) and I disable the OP menu with F3, the chats transparency BG will be removed. 

FR: Option to keep the background when OP menu is disabled.

**Comment by codecat** [comment]
I think this already exists, no? In the settings, under "Appearance", set "Background style" to "Transparent".

**Comment by salem83** [comment]
That was it. Thanks
